/**
 * Provider projection (AIEF-000 §6, §39, §55.4).
 *
 * A provider file is a projection of the composed configuration, never a policy
 * source. This module renders that projection and detects drift between it and
 * what is committed.
 *
 * The projection owns a **managed region** inside an otherwise hand-authored
 * file. A fully generated entry point would have to invent what the composition
 * does not know — a project summary, a directory map, repository-specific traps
 * — and inventing it is how a projection quietly becomes a policy source. §55.4
 * permits exactly this: reproducible from the composed source, or explicitly
 * linked back to it.
 *
 * Everything outside the markers belongs to the author. Everything inside is
 * overwritten without warning.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/** The neutral entry point both documented adapters consume (§39). */
export const PROJECTION_TARGET = 'AGENTS.md';

export const BEGIN = '<!-- aief:begin -->';
export const END = '<!-- aief:end -->';

const NOTE =
  '_Generated by `aief render`. Everything between the markers is overwritten — ' +
  'edit the Foundation, the Stack Profile or the Project Profile instead (§6)._';

/**
 * Renders a GFM table with every column padded to its widest cell.
 *
 * That is the canonical form most Markdown formatters produce. Emitting it
 * directly keeps the entry point inside the repository's format gate: an
 * unpadded table would be reformatted on every run, and the reformatted file
 * would then read as projection drift — two gates fighting over one file.
 */
function mdTable(headers, rows) {
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map((r) => String(r[i] ?? '').length)),
  );
  const line = (cells) =>
    `| ${cells.map((c, i) => String(c ?? '').padEnd(widths[i])).join(' | ')} |`;
  return [
    line(headers),
    `| ${widths.map((w) => '-'.repeat(Math.max(w, 3))).join(' | ')} |`,
    ...rows.map(line),
  ];
}

function bindingLabel(rule) {
  if (!rule.binding) return '—';
  if (rule.binding.kind === 'engine') return '`aief compose`';
  return `\`${rule.binding.command}\``;
}

/**
 * Renders the managed region from a composition result.
 *
 * Enforced rules are listed in full because they change what an agent may do.
 * Advisory rules are counted, not enumerated: 50-odd intents in an always-loaded
 * file spends the context budget (§13) on guidance that blocks nothing.
 */
export function renderProjection(result) {
  const m = result.meta;
  const lines = [BEGIN, '', NOTE, ''];

  lines.push(
    `Foundation **${m.foundation_version}** · conformance **${m.conformance}** · ` +
      `stacks ${m.stacks.length ? m.stacks.map((s) => `\`${s}\``).join(', ') : '_none_'}`,
  );
  lines.push('');

  const enforced = result.rules.filter((r) => r.mode === 'enforced');
  lines.push(`## Enforced — ${enforced.length} rule(s)`);
  lines.push('');
  lines.push('These are checked. Violating one fails a gate, not a review.');
  lines.push('');
  lines.push(
    ...mdTable(
      ['Rule', 'Intent', 'Enforced by'],
      enforced.map((r) => [`\`${r.id}\``, r.intent, bindingLabel(r)]),
    ),
  );
  lines.push('');

  const commands = [
    ...new Set(
      enforced
        .filter((r) => r.binding?.kind === 'stack')
        .map((r) => `${r.binding.command}  # ${r.binding.capability}`),
    ),
  ].sort();
  if (commands.length) {
    lines.push('## Commands the gates run');
    lines.push('');
    lines.push('```text');
    for (const c of commands) lines.push(c);
    lines.push('```');
    lines.push('');
  }

  const advisory = result.rules.filter((r) => r.mode === 'advisory');
  const byNamespace = new Map();
  for (const r of advisory) {
    const ns = String(r.id).split('-').slice(0, 2).join('-');
    byNamespace.set(ns, (byNamespace.get(ns) ?? 0) + 1);
  }
  lines.push(`## Advisory — ${advisory.length} rule(s)`);
  lines.push('');
  lines.push(
    'Not enumerated here on purpose: an always-loaded file spends context on every line ' +
      'it carries (§13). Run `aief compose --verbose` for the full list.',
  );
  lines.push('');
  for (const [ns, count] of [...byNamespace].sort()) {
    lines.push(`- \`${ns}\` — ${count}`);
  }
  lines.push('');

  const scoped = result.rules.filter((r) => r.scope && r.scope !== 'global');
  if (scoped.length) {
    lines.push('## Scoped rules');
    lines.push('');
    for (const r of scoped) {
      const where = r.scope.include?.join(', ') ?? r.scope.type;
      lines.push(`- \`${r.id}\` — ${where}`);
    }
    lines.push('');
  }

  const waived = result.rules.filter((r) => r.waiver);
  if (waived.length) {
    lines.push('## Active waivers');
    lines.push('');
    for (const r of waived) {
      const until = r.waiver.expires_at ? ` until ${r.waiver.expires_at}` : ' with no expiry';
      lines.push(`- \`${r.id}\` — ${r.waiver.scope}${until}: ${r.waiver.reason.trim()}`);
    }
    lines.push('');
  }

  lines.push(END);
  return lines.join('\n');
}

/** Splits a file into what precedes the region, and what follows it. */
function locateRegion(text) {
  const start = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end < start) return null;
  return { before: text.slice(0, start), current: text.slice(start, end + END.length) };
}

/**
 * @returns {{status: 'ok'|'drift'|'absent'|'missing-file', current?: string}}
 */
export function checkProjection(cwd, block, target = PROJECTION_TARGET) {
  const file = join(cwd, target);
  if (!existsSync(file)) return { status: 'missing-file' };
  const region = locateRegion(readFileSync(file, 'utf8'));
  if (!region) return { status: 'absent' };
  return region.current === block ? { status: 'ok' } : { status: 'drift', current: region.current };
}

/**
 * Writes the region into the target, appending it if the markers are absent.
 * Content outside the markers is preserved byte for byte.
 */
export function writeProjection(cwd, block, target = PROJECTION_TARGET) {
  const file = join(cwd, target);
  const text = existsSync(file) ? readFileSync(file, 'utf8') : `# ${target}\n`;
  const region = locateRegion(text);

  const next = region
    ? text.slice(0, text.indexOf(BEGIN)) + block + text.slice(text.indexOf(END) + END.length)
    : `${text.replace(/\s*$/, '')}\n\n${block}\n`;

  writeFileSync(file, next, 'utf8');
  return file;
}
